### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by avantassel** [fxb/php-last.fm-api#2]
Any chance you could give a simple example of calling artist.getInfo?  Having trouble how to make the call and what to include.  Thanks.

**Comment by avantassel** [comment]
nevermind, found it. Here is an example.

include 'lastfm.api.php';
$info = Artist::getInfo($artist);

print_r($info);

**Comment by Cruel** [comment]
Is this an out-dated example? Otherwise how do you called the static method when Caller's setApiKey needs a class instance?

**Comment by reallistic** [comment]
Cruel. Next time use google ;)

```
require "/src/lastfm.api.php";

// set api key
CallerFactory::getDefaultCaller()->setApiKey(LAST_FM_API_KEY);

// search for the Coldplay band
$artistName = "Coldplay";
$limit = 1;
$results = Artist::search($artistName, $limit);
```

http://www.sitepoint.com/using-the-last-fm-api/
